# Generated by Django 5.2.10 on 2026-01-07 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis_code', models.CharField(help_text='Primary ICD-10 diagnosis code (e.g., G70.00)', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid ICD-10 code format. Expected format: A00 or A00.0000', regex='^[A-Z]\\d{2}(\\.\\d{1,4})?$')])),
                ('primary_diagnosis_description', models.CharField(blank=True, help_text='Description of the primary diagnosis', max_length=255)),
                ('additional_diagnoses', models.JSONField(blank=True, default=list, help_text='List of additional ICD-10 codes')),
                ('medication_name', models.CharField(help_text='Name of the medication (e.g., IVIG)', max_length=255)),
                ('medication_history', models.JSONField(blank=True, default=list, help_text='List of previous medications')),
                ('patient_records', models.TextField(help_text='Clinical notes and patient records for care plan generation')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The generated care plan content')),
                ('model_used', models.CharField(help_text='The AI model used for generation (e.g., claude-sonnet-4-20250514)', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_ms', models.IntegerField(blank=True, help_text='Time taken to generate the care plan in milliseconds', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='careplan.order')),
            ],
            options={
                'verbose_name': 'Care Plan',
                'verbose_name_plural': 'Care Plans',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mrn', models.CharField(help_text='Medical Record Number - exactly 6 digits', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='MRN must be exactly 6 digits', regex='^\\d{6}$')])),
                ('dob', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['mrn'], name='careplan_pa_mrn_68dfb7_idx'), models.Index(fields=['last_name', 'first_name'], name='careplan_pa_last_na_475dc2_idx'), models.Index(fields=['last_name', 'first_name', 'dob'], name='careplan_pa_last_na_d42580_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='careplan.patient'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name of the provider (e.g., 'Dr. Jane Smith')", max_length=255)),
                ('npi', models.CharField(help_text='National Provider Identifier - exactly 10 digits', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NPI must be exactly 10 digits', regex='^\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['npi'], name='careplan_pr_npi_4cb1e1_idx'), models.Index(fields=['name'], name='careplan_pr_name_a6afcb_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='careplan.provider'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='careplan_or_status_6250c7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['patient', 'medication_name'], name='careplan_or_patient_99d4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='careplan_or_created_757ca1_idx'),
        ),
    ]
