# Generated by Django 5.2.10 on 2026-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='1900-01-01', help_text='Date of birth (required for care plan generation)'),
        ),
    ]
