# Generated by Django 5.2.10 on 2026-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0003_alter_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last manual edit', null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether the care plan content has been manually edited'),
        ),
    ]
